<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>XHP</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;\?(?i:php|=)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.php</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.php</string>
			<key>end</key>
			<string>(\?)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.php</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.php</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.block.php</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\byield\b</string>
					<key>name</key>
					<string>keyword.control.directive.hiphop.php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.php#language</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b([^\s{}&lt;&gt;""]+)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.$1.xhp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=/?&gt;|\s)</string>
					<key>name</key>
					<string>meta.property.$1.xhp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G=</string>
							<key>name</key>
							<string>punctuation.separator.key-value.tag.xml.xhp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#xhp-embedded</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.xhp</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>meta.scope.value.string.xhp</string>
							<key>end</key>
							<string>"</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.xhp</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.double.xhp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block_tag</key>
		<dict>
			<key>begin</key>
			<string>(?=(&lt;)([^\s&lt;/&gt;]+))</string>
			<key>contentName</key>
			<string>meta.block.inner.${2/:/./g}.xhp</string>
			<key>end</key>
			<string>(&lt;/)(\2)(&gt;)|(/&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.end.${2/:/./g}.xhp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.${2/:/./g}.xhp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.begin.${2/:/./g}.xhp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.scope.tag.block.${2/:/./g}.xhp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(&lt;)([^\s&lt;/&gt;]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.${2/:/./g}.xhp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;|(?=/&gt;)</string>
					<key>name</key>
					<string>meta.tag.block.begin.${2/:/./g}.xhp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attr</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xhp-embedded</string>
				</dict>
			</array>
		</dict>
		<key>xhp-embedded</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.php</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.php</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.php</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.block.php</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.php#language</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.xhp</string>
	<key>uuid</key>
	<string>85DBBBB9-5E7F-4EF0-83EB-8F43233A09E2</string>
</dict>
</plist>
